<a href="https://colab.research.google.com/github/efesefe/ACCOUNT/blob/master/Machine_Learning_Bug_Finder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [338]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import glob
import os
from sklearn.model_selection import cross_val_score

In [339]:
allData = pd.concat(map(pd.read_csv, glob.glob(os.path.join('', "*.csv"))))
allData.drop('name.1', axis=1, inplace=True)
allData.drop('version', axis=1, inplace=True)
X = allData.iloc[:, :-1].values
y = allData.iloc[:, -1].values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = pd.DataFrame(ct.fit_transform(X))
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = pd.DataFrame(scaler.transform(X))

In [340]:
from sklearn.neighbors import LocalOutlierFactor
clf = LocalOutlierFactor(n_neighbors = 20, contamination = 0.1)
clf.fit_predict(X)
df_scores = clf.negative_outlier_factor_
esik_deger = np.sort(df_scores)[13]
aykiri_tf = df_scores > esik_deger
baski_deger =  X[df_scores == esik_deger]
aykirilar = X[~aykiri_tf]
aykirilar.to_records(index = False)
res = aykirilar.to_records(index = False)
res[:] = baski_deger.to_records(index = False)
X[~aykiri_tf] = pd.DataFrame(res, index = X[~aykiri_tf].index)
y[y > 0] = 1
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

###İBRAHİM EFE ERER

In [341]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)
print(accuracy_score(y_test, rfc_pred))
print(confusion_matrix(y_test, rfc_pred))
print("10-Fold Cross validation score")
print(cross_val_score(rfc,X,y,cv=10,scoring='accuracy').mean())

0.8537378114842904
[[544  41]
 [ 94 244]]
10-Fold Cross validation score
0.7292231268370097


In [342]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
clf = BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=0).fit(X, y)
bagging_result = clf.predict(X_test)
print(accuracy_score(y_test, bagging_result))
print(confusion_matrix(y_test, bagging_result))
print("10-Fold Cross validation score")
print(cross_val_score(clf,X,y,cv=10,scoring='accuracy').mean())

0.8407367280606717
[[552  33]
 [114 224]]
10-Fold Cross validation score
0.6932637499882619


###CAN ATEŞ:

In [334]:
from sklearn.naive_bayes import GaussianNB

bayes = GaussianNB()
bayes.fit(X_train , y_train)

y_pred = bayes.predict(X_test)

print(accuracy_score(y_test,y_pred))

print("10-Fold Cross validation score")
print(cross_val_score(bayes,X,y,cv=10,scoring='accuracy').mean())

0.7919826652221018
10-Fold Cross validation score
0.6513991792733659


In [335]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print("10-Fold Cross validation score")
print(cross_val_score(knn,X,y,cv=10,scoring='accuracy').mean())

0.8309859154929577
10-Fold Cross validation score
0.6941318984702933


##YAZGI KAVUKÇU

In [336]:
from sklearn.tree import DecisionTreeClassifier
regr = DecisionTreeClassifier()
regr.fit(X_train, y_train)
result = regr.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, result))
print(confusion_matrix(y_test, result))
print("10-Fold Cross validation score")
print(cross_val_score(regr,X,y,cv=10,scoring='accuracy').mean())

0.7941495124593716
[[494 109]
 [ 81 239]]
10-Fold Cross validation score
0.6900193443577392


In [337]:
from sklearn.svm import SVC

svc = SVC()

svc.fit(X_train , y_train)

y_pred = svc.predict(X_test)

print(accuracy_score(y_test,y_pred))

print("10-Fold Cross validation score")
print(cross_val_score(svc,X,y,cv=10,scoring='accuracy').mean())

0.8223185265438786
[[542  61]
 [103 217]]
10-Fold Cross validation score
0.6919580058408692
